
  CREATE TABLE "C##SPRINGEDU"."MEMBER" 
   (	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
			"PW" VARCHAR2(10 BYTE), 
			"TEL" VARCHAR2(13 BYTE), 
			"NICKNAME" VARCHAR2(30 BYTE), 
			"GENDER" CHAR(3 BYTE), 
			"REGION" VARCHAR2(30 BYTE), 
			"BIRTH" DATE, 
			"CDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
			"UDATE" TIMESTAMP (6), 
			"PIC" BLOB, 
			"FSIZE" VARCHAR2(45 BYTE), 
			"FTYPE" VARCHAR2(50 BYTE), 
			"COL1" VARCHAR2(20 BYTE), 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEMBER_CHK1" CHECK (gender in('남','여')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."ID" IS 'ex)admin@google.com';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."PW" IS '8~10자리,특수문자포함';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."TEL" IS '''-''포함';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."GENDER" IS '성별(''남'',''여'')';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."REGION" IS '지역';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."BIRTH" IS '생년월일(''YYYYMMDD'')';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."CDATE" IS '생성일시';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."UDATE" IS '변경일시';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."PIC" IS '회원사진(GIF,JPEG,PNG)';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."FSIZE" IS '파일크기';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."FTYPE" IS '파일타입';
   COMMENT ON COLUMN "C##SPRINGEDU"."MEMBER"."COL1" IS '임시';

